### ISSUE TITLE
[ZAP] Cross-Domain Misconfiguration

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-web#59]
Header "Access-Control-Allow-Origin" in 62 responses is set incorrectly. ZAP priority Medium.

**Comment by kianapaz** [comment]
Originally the corsOptions variable "origin" was set to a wildcard "*" where the access control allows a wildcard, which is a vulnerability. After security fixes, it is now changed to "origin: 'http://localhost:3000'" which mitigates this vulnerability because it no longer tells code from any origin that it can access the site. 
This was tested using a separate server, that sent an attack html that set credentials to true. It was not successful and returned a 404 error from the site. I followed this site for the testing: https://github.com/cactuz/cors-tester-from-browser
This security vulnerability is now mitigated because of the change. Closing the issue.
